---
{
   "kind": "pipeline",
   "name": "rspamd_amd64",
   "platform": {
      "arch": "amd64",
      "os": "linux"
   },
   "steps": [
      {
         "image": "rspamd/drone-docker-plugin",
         "name": "pkg_amd64",
         "privileged": true,
         "settings": {
            "build_args": [
               "RSPAMD_VERSION=${DRONE_SEMVER_SHORT}",
               "TARGETARCH=amd64"
            ],
            "dockerfile": "Dockerfile.pkg",
            "password": {
               "from_secret": "docker_password"
            },
            "platform": "linux/amd64",
            "repo": "rspamd/rspamd",
            "tags": [
               "pkg-amd64-${DRONE_SEMVER_SHORT}-${DRONE_SEMVER_BUILD}"
            ],
            "target": "pkg",
            "username": {
               "from_secret": "docker_username"
            }
         }
      },
      {
         "depends_on": [
            "pkg_amd64"
         ],
         "image": "rspamd/drone-docker-plugin",
         "name": "install_amd64",
         "privileged": true,
         "settings": {
            "build_args": [
               "LONG_VERSION=${DRONE_SEMVER_SHORT}-${DRONE_SEMVER_BUILD}",
               "TARGETARCH=amd64"
            ],
            "dockerfile": "Dockerfile",
            "password": {
               "from_secret": "docker_password"
            },
            "platform": "linux/amd64",
            "repo": "rspamd/rspamd",
            "squash": true,
            "tags": [
               "image-amd64-${DRONE_SEMVER_SHORT}-${DRONE_SEMVER_BUILD}"
            ],
            "target": "install",
            "username": {
               "from_secret": "docker_username"
            }
         }
      },
      {
         "depends_on": [
            "pkg_amd64"
         ],
         "image": "rspamd/drone-docker-plugin",
         "name": "install_asan_amd64",
         "privileged": true,
         "settings": {
            "build_args": [
               "LONG_VERSION=${DRONE_SEMVER_SHORT}-${DRONE_SEMVER_BUILD}",
               "TARGETARCH=amd64",
               "ASAN_TAG=-asan"
            ],
            "dockerfile": "Dockerfile",
            "password": {
               "from_secret": "docker_password"
            },
            "platform": "linux/amd64",
            "repo": "rspamd/rspamd",
            "squash": true,
            "tags": [
               "image-asan-amd64-${DRONE_SEMVER_SHORT}-${DRONE_SEMVER_BUILD}"
            ],
            "target": "install",
            "username": {
               "from_secret": "docker_username"
            }
         }
      }
   ],
   "trigger": {
      "event": {
         "include": [
            "tag"
         ]
      }
   },
   "type": "docker"
}
---
{
   "kind": "pipeline",
   "name": "rspamd_arm64",
   "platform": {
      "arch": "arm64",
      "os": "linux"
   },
   "steps": [
      {
         "image": "rspamd/drone-docker-plugin",
         "name": "pkg_arm64",
         "privileged": true,
         "settings": {
            "build_args": [
               "RSPAMD_VERSION=${DRONE_SEMVER_SHORT}",
               "TARGETARCH=arm64"
            ],
            "dockerfile": "Dockerfile.pkg",
            "password": {
               "from_secret": "docker_password"
            },
            "platform": "linux/arm64",
            "repo": "rspamd/rspamd",
            "tags": [
               "pkg-arm64-${DRONE_SEMVER_SHORT}-${DRONE_SEMVER_BUILD}"
            ],
            "target": "pkg",
            "username": {
               "from_secret": "docker_username"
            }
         }
      },
      {
         "depends_on": [
            "pkg_arm64"
         ],
         "image": "rspamd/drone-docker-plugin",
         "name": "install_arm64",
         "privileged": true,
         "settings": {
            "build_args": [
               "LONG_VERSION=${DRONE_SEMVER_SHORT}-${DRONE_SEMVER_BUILD}",
               "TARGETARCH=arm64"
            ],
            "dockerfile": "Dockerfile",
            "password": {
               "from_secret": "docker_password"
            },
            "platform": "linux/arm64",
            "repo": "rspamd/rspamd",
            "squash": true,
            "tags": [
               "image-arm64-${DRONE_SEMVER_SHORT}-${DRONE_SEMVER_BUILD}"
            ],
            "target": "install",
            "username": {
               "from_secret": "docker_username"
            }
         }
      },
      {
         "depends_on": [
            "pkg_arm64"
         ],
         "image": "rspamd/drone-docker-plugin",
         "name": "install_asan_arm64",
         "privileged": true,
         "settings": {
            "build_args": [
               "LONG_VERSION=${DRONE_SEMVER_SHORT}-${DRONE_SEMVER_BUILD}",
               "TARGETARCH=arm64",
               "ASAN_TAG=-asan"
            ],
            "dockerfile": "Dockerfile",
            "password": {
               "from_secret": "docker_password"
            },
            "platform": "linux/arm64",
            "repo": "rspamd/rspamd",
            "squash": true,
            "tags": [
               "image-asan-arm64-${DRONE_SEMVER_SHORT}-${DRONE_SEMVER_BUILD}"
            ],
            "target": "install",
            "username": {
               "from_secret": "docker_username"
            }
         }
      }
   ],
   "trigger": {
      "event": {
         "include": [
            "tag"
         ]
      }
   },
   "type": "docker"
}
---
{
   "depends_on": [
      "rspamd_amd64",
      "rspamd_arm64"
   ],
   "kind": "pipeline",
   "name": "rspamd_multiarch",
   "steps": [
      {
         "image": "plugins/manifest",
         "name": "multiarch_image",
         "settings": {
            "password": {
               "from_secret": "docker_password"
            },
            "platforms": [
               "linux/amd64",
               "linux/arm64"
            ],
            "target": "rspamd/rspamd:image-${DRONE_SEMVER_SHORT}-${DRONE_SEMVER_BUILD}",
            "template": "rspamd/rspamd:image-ARCH-${DRONE_SEMVER_SHORT}-${DRONE_SEMVER_BUILD}",
            "username": {
               "from_secret": "docker_username"
            }
         }
      },
      {
         "image": "plugins/manifest",
         "name": "multiarch_asan_image",
         "settings": {
            "password": {
               "from_secret": "docker_password"
            },
            "platforms": [
               "linux/amd64",
               "linux/arm64"
            ],
            "target": "rspamd/rspamd:image-asan-${DRONE_SEMVER_SHORT}-${DRONE_SEMVER_BUILD}",
            "template": "rspamd/rspamd:image-asan-ARCH-${DRONE_SEMVER_SHORT}-${DRONE_SEMVER_BUILD}",
            "username": {
               "from_secret": "docker_username"
            }
         }
      }
   ],
   "trigger": {
      "event": {
         "include": [
            "tag"
         ]
      }
   },
   "type": "docker"
}
---
{
   "kind": "pipeline",
   "name": "prepromo_amd64",
   "platform": {
      "arch": "amd64",
      "os": "linux"
   },
   "steps": [
      {
         "commands": [
            "apt-get update",
            "apt-get install -y git miltertest python3 python3-dev python3-pip python3-venv redis-server",
            "python3 -mvenv $DRONE_WORKSPACE/venv",
            "bash -c \"source $DRONE_WORKSPACE/venv/bin/activate && pip3 install --no-cache --disable-pip-version-check --no-binary :all: setuptools==57.5.0\"",
            "bash -c \"source $DRONE_WORKSPACE/venv/bin/activate && pip3 install --no-cache --disable-pip-version-check --no-binary :all: demjson psutil requests robotframework tornado\"",
            "git clone -b ${DRONE_SEMVER_SHORT} https://github.com/rspamd/rspamd.git",
            "git -C rspamd cherry-pick 80a16124fbc6af2245231b8c2d03bea4182c181d d2fbce7dd9931431a4446e05aff8fba89b36d875 12e835dd8c2be2488af43c2cdf65d23774f84b53 ca78b09ba291c702707ac24923e53e153f4e9a11",
            "RSPAMD_INSTALLROOT=/usr bash -c \"source $DRONE_WORKSPACE/venv/bin/activate && umask 0000 && robot --removekeywords wuks --exclude isbroken $DRONE_WORKSPACE/rspamd/test/functional/cases\""
         ],
         "image": "rspamd/rspamd:image-amd64-${DRONE_SEMVER_SHORT}-${DRONE_SEMVER_BUILD}",
         "name": "pre_promotion_test",
         "user": "root"
      }
   ],
   "trigger": {
      "event": [
         "promote"
      ]
   },
   "type": "docker"
}
---
{
   "kind": "pipeline",
   "name": "prepromo_arm64",
   "platform": {
      "arch": "arm64",
      "os": "linux"
   },
   "steps": [
      {
         "commands": [
            "apt-get update",
            "apt-get install -y git miltertest python3 python3-dev python3-pip python3-venv redis-server",
            "python3 -mvenv $DRONE_WORKSPACE/venv",
            "bash -c \"source $DRONE_WORKSPACE/venv/bin/activate && pip3 install --no-cache --disable-pip-version-check --no-binary :all: setuptools==57.5.0\"",
            "bash -c \"source $DRONE_WORKSPACE/venv/bin/activate && pip3 install --no-cache --disable-pip-version-check --no-binary :all: demjson psutil requests robotframework tornado\"",
            "git clone -b ${DRONE_SEMVER_SHORT} https://github.com/rspamd/rspamd.git",
            "git -C rspamd cherry-pick 80a16124fbc6af2245231b8c2d03bea4182c181d d2fbce7dd9931431a4446e05aff8fba89b36d875 12e835dd8c2be2488af43c2cdf65d23774f84b53 ca78b09ba291c702707ac24923e53e153f4e9a11",
            "RSPAMD_INSTALLROOT=/usr bash -c \"source $DRONE_WORKSPACE/venv/bin/activate && umask 0000 && robot --removekeywords wuks --exclude isbroken $DRONE_WORKSPACE/rspamd/test/functional/cases\""
         ],
         "image": "rspamd/rspamd:image-arm64-${DRONE_SEMVER_SHORT}-${DRONE_SEMVER_BUILD}",
         "name": "pre_promotion_test",
         "user": "root"
      }
   ],
   "trigger": {
      "event": [
         "promote"
      ]
   },
   "type": "docker"
}
---
{
   "depends_on": [
      "prepromo_amd64",
      "prepromo_arm64"
   ],
   "kind": "pipeline",
   "name": "promotion_multiarch",
   "steps": [
      {
         "image": "plugins/manifest",
         "name": "promote_multiarch",
         "settings": {
            "password": {
               "from_secret": "docker_password"
            },
            "platforms": [
               "linux/amd64",
               "linux/arm64"
            ],
            "tags": [
               "latest",
               "${DRONE_SEMVER_MAJOR}.${DRONE_SEMVER_MINOR}"
            ],
            "target": "rspamd/rspamd:${DRONE_SEMVER_SHORT}",
            "template": "rspamd/rspamd:image-ARCH-${DRONE_SEMVER_SHORT}-${DRONE_SEMVER_BUILD}",
            "username": {
               "from_secret": "docker_username"
            }
         }
      }
   ],
   "trigger": {
      "event": [
         "promote"
      ]
   },
   "type": "docker"
}
---
{
   "depends_on": [
      "prepromo_amd64",
      "prepromo_arm64"
   ],
   "kind": "pipeline",
   "name": "promotion_multiarch_asan",
   "steps": [
      {
         "image": "plugins/manifest",
         "name": "promote_multiarch_asan",
         "settings": {
            "password": {
               "from_secret": "docker_password"
            },
            "platforms": [
               "linux/amd64",
               "linux/arm64"
            ],
            "tags": [
               "asan-latest",
               "asan-${DRONE_SEMVER_MAJOR}.${DRONE_SEMVER_MINOR}"
            ],
            "target": "rspamd/rspamd:asan-${DRONE_SEMVER_SHORT}",
            "template": "rspamd/rspamd:image-asan-ARCH-${DRONE_SEMVER_SHORT}-${DRONE_SEMVER_BUILD}",
            "username": {
               "from_secret": "docker_username"
            }
         }
      }
   ],
   "trigger": {
      "event": [
         "promote"
      ]
   },
   "type": "docker"
}
---
{
   "hmac": "429a888f569721b63ce7061ad4f6b0dc58659f51c4e547654c62918f1c82b9a8",
   "kind": "signature"
}
...
