name: Push new tag with version bump

runs:
  using: "composite"
  steps:
    - name: Create new patch release
      shell: bash
      working-directory: ${{ github.workspace }}
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        LATEST_TAG=`git tag --list "v[0-9]*.[0-9]*.[0-9]*\+[0-9]*" --sort=-v:refname | head -n 1`
        RELEASE_VERSION=${LATEST_TAG%%+*}
        BUILD_VERSION=${LATEST_TAG##*+}
        NEW_BUILD_VERSION=$((BUILD_VERSION + 1))
        NEW_TAG="${RELEASE_VERSION}+${NEW_BUILD_VERSION}"
        echo "Latest tag: $LATEST_TAG"
        echo "New tag: $NEW_TAG"
        git tag $NEW_TAG $LATEST_TAG
        git push origin $NEW_TAG
        gh workflow run release --ref $NEW_TAG
