FROM cznic/knot-resolver

RUN	mkdir /data && \
	chown 1000:1000 /data && \
	chown 1000:1000 /etc/knot-resolver && \
	chown 1000:1000 /etc/knot-resolver/root.keys

WORKDIR /data

USER 1000:1000
EXPOSE 443/TCP 53/TCP 53/UDP
