name: build_test_promote

on:
  workflow_call:
    inputs:
      dockerhub_name:
        default: rspamd/rspamd
        required: false
        type: string
      nightly:
        default: true
        required: false
        type: boolean

jobs:
  build_amd64:
    uses: ./.github/workflows/docker_build.yml
    with:
      nightly: ${{ inputs.nightly }}
      platform: amd64
    permissions:
      packages: write
      contents: read
    secrets: inherit

  build_arm64:
    uses: ./.github/workflows/docker_build.yml
    with:
      nightly: ${{ inputs.nightly }}
      platform: arm64
    permissions:
      packages: write
      contents: read
    secrets: inherit

  test_amd64:
    needs: [build_amd64]
    uses: ./.github/workflows/rspamd_test.yml
    with:
      image: ghcr.io/${{ github.repository }}@${{ needs.build_amd64.outputs.digest_release }}
      tag: "${{ needs.build_amd64.outputs.tag }}"

  test_arm64:
    needs: [build_arm64]
    uses: ./.github/workflows/rspamd_test.yml
    with:
      image: ghcr.io/${{ github.repository }}@${{ needs.build_arm64.outputs.digest_release }}
      tag: "${{ needs.build_arm64.outputs.tag }}"
      platform: arm64

  get_tags:
    outputs:
      dockerhub_tags_asan: ${{ steps.compute.outputs.dockerhub_tags_asan }}
      dockerhub_tags_release: ${{ steps.compute.outputs.dockerhub_tags_release }}
      ghcr_tags_asan: ${{ steps.compute.outputs.ghcr_tags_asan }}
      ghcr_tags_release: ${{ steps.compute.outputs.ghcr_tags_release }}
      ghcr_tags_package: ${{ steps.compute.outputs.ghcr_tags_package }}
      dockerhub_tags_package: ${{ steps.compute.outputs.dockerhub_tags_package }}
    runs-on: "ubuntu-22.04"
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Compute tags
        id: compute
        uses: ./.github/actions/compute-tags
        with:
          nightly: ${{ inputs.nightly }}
          dockerhub_name: ${{ inputs.dockerhub_name }}

  promote:
    needs: [build_amd64, build_arm64, get_tags, test_amd64, test_arm64]
    uses: ./.github/workflows/promote.yml
    permissions:
      packages: write
      contents: read
    with:
      images: ghcr.io/${{ github.repository }}@${{ needs.build_amd64.outputs.digest_release }},ghcr.io/${{ github.repository }}@${{ needs.build_arm64.outputs.digest_release }}
      images_asan: ghcr.io/${{ github.repository }}@${{ needs.build_amd64.outputs.digest_asan }},ghcr.io/${{ github.repository }}@${{ needs.build_arm64.outputs.digest_asan }}
      images_package: ghcr.io/${{ github.repository }}@${{ needs.build_amd64.outputs.digest_package }},ghcr.io/${{ github.repository }}@${{ needs.build_arm64.outputs.digest_package }}
      dockerhub_tags_asan: "${{ needs.get_tags.outputs.dockerhub_tags_asan }}"
      dockerhub_tags_release: "${{ needs.get_tags.outputs.dockerhub_tags_release }}"
      ghcr_tags_asan: "${{ needs.get_tags.outputs.ghcr_tags_asan }}"
      ghcr_tags_release: "${{ needs.get_tags.outputs.ghcr_tags_release }}"
      ghcr_tags_package: "${{ needs.get_tags.outputs.ghcr_tags_package }}"
      dockerhub_tags_package: "${{ needs.get_tags.outputs.dockerhub_tags_package }}"
    secrets: inherit
