name: release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+\\+[0-9]+"
  workflow_dispatch:

concurrency:
  group: rspamd-docker-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  build_test_promote:
    uses: ./.github/workflows/build_test_promote.yml
    with:
      nightly: false
    permissions:
      packages: write
      contents: read
    secrets: inherit
